
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# System dependencies
RUN apt-get update && apt-get install -y \
    git curl build-essential libpq-dev && \
    rm -rf /var/lib/apt/lists/*

# Copy files
COPY pyproject.toml poetry.lock ./

# Install Poetry
RUN pip install poetry

# Install all deps (incl. dev)
RUN poetry config virtualenvs.create false && \
    poetry install --no-root

# Copy rest of project
COPY . .

# Expose useful ports for dev
EXPOSE 5000 8000 8501 8080

# Default command
CMD ["poetry", "run", "streamlit", "run", "app/main.py"]
