# pytest.ini
[pytest]
markers =
    integration: mark tests as integration (hit real MLflow server)
filterwarnings =
    # ignore Pydantic class-based Config deprecation warning
    ignore:Support for class-based `config` is deprecated:DeprecationWarning
